site_name: Spark Docs
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  palette:
    primary: custom
  font:
    text: Inter
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
plugins:
  - awesome-pages
  - search
markdown_extensions:
  meta: {} # Add front matter to a document
  admonition: {} # Makes things pretty
  pymdownx.superfences: {} # Nestled code
  attr_list: {} # Add HTML attributes and CSS classes to Markdown elements
  pymdownx.tabbed: # Content tabs
    alternate_style: true
  pymdownx.details: {} # Additional features to admonition
  pymdownx.caret: {} # Formatting Extension
  pymdownx.critic: {} # Alternate Formatting Extension
  pymdownx.mark: {} # Formatting Extension
  pymdownx.tilde: {} # Formatting Extension
  pymdownx.keys: {} # Visual keyboard keys extension
  def_list: {}
  pymdownx.snippets: 
    auto_append: 
    - includes/abbreviations.md
  pymdownx.tasklist:
    custom_checkbox: true
  pymdownx.emoji: # Allows emoji style inline embeds for icons
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
  md_in_html: {} # Allows markdown to be used in HTML
  abbr: {} # Adds abbreviations